spring:
  application.name: stock-calculator
  sql.init.mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
stock:
  api:
    url: https://finnhub.io/api/v1
    api-key: "cum3dupr01qovv71b40gcum3dupr01qovv71b410"