spring:
  application.name: stock-calculator
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
stock:
  prices-api:
    url: https://finnhub.io/api/v1
    api-key: ${FINNHUB_API_KEY}
    enabled: false
  transactions-api:
    url: https://demo.trading212.com
    api-key: ${TRANSACTIONS_API_KEY}
  plaid-api:
    client-id: ${PLAID_CLIENT_ID}
    secret: ${PLAID_SECRET}
    environment: ${PLAID_ENVIRONMENT}
auth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  jwt:
    secret: ${JWT_SECRET}




