spring:
  application.name: stock-calculator
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
stock:
  api:
    url: https://finnhub.io/api/v1
    api-key: ${FINNHUB_API_KEY}
